/**
 * Example showing how to use @thepia/flows-db types in the admin demo
 *
 * This file demonstrates importing and using the type-safe Flows data types
 * from the workspace package.
 */

import type {
	FlowsJourney,
	FlowsTask,
	FlowsAttachment,
	FlowsEvidence,
	FlowsEntityCreate,
	FlowsEntityUpdate,
	FlowsDBProcedures,
	ProcedureInput,
	ProcedureOutput
} from '@thepia/flows-db/types';

/**
 * Example: Create a new journey with full type safety
 */
export function createExampleJourney(): FlowsEntityCreate<FlowsJourney> {
	return {
		client_id: 'demo',
		app_id: 'flows',
		title: 'Employee Onboarding',
		description: 'Complete all onboarding tasks',
		status: 'invited',
		invited_at: new Date(),
		owner_id: 'manager-123',
		participants: ['employee-456'],
		metadata: {
			department: 'Engineering',
			start_date: '2025-11-01'
		}
		// Note: id, created_at, updated_at are excluded (generated by system)
	};
}

/**
 * Example: Update a journey with partial data
 */
export function createJourneyUpdate(): FlowsEntityUpdate<FlowsJourney> {
	return {
		status: 'active',
		started_at: new Date(),
		progress_percentage: 25
		// All fields are optional in updates
	};
}

/**
 * Example: Type-safe query input
 */
export function createTaskQuery(journeyId: string): ProcedureInput<'query.tasks'> {
	return {
		filter: {
			eq: { journey_id: journeyId, status: 'pending' }
		},
		orderBy: [{ column: 'order', ascending: true }],
		limit: 10
	};
}

/**
 * Example: Full journey with tasks
 */
export interface JourneyWithTasks {
	journey: FlowsJourney;
	tasks: FlowsTask[];
	attachments: FlowsAttachment[];
	evidence: FlowsEvidence[];
}

/**
 * Example: Mock database client using procedure types
 */
export class MockFlowsDBClient {
	async queryTasks(
		input: ProcedureInput<'query.tasks'>
	): Promise<ProcedureOutput<'query.tasks'>> {
		// In real implementation, this would call the service worker or native bridge
		console.log('Querying tasks with filter:', input.filter);
		return [];
	}

	async insertJourney(
		input: ProcedureInput<'mutation.insertJourney'>
	): Promise<ProcedureOutput<'mutation.insertJourney'>> {
		console.log('Creating journey:', input.data);
		// Return type is automatically FlowsJourney
		return {
			id: crypto.randomUUID(),
			...input.data,
			created_at: new Date(),
			updated_at: new Date()
		};
	}

	async updateTask(
		input: ProcedureInput<'mutation.updateTask'>
	): Promise<ProcedureOutput<'mutation.updateTask'>> {
		console.log('Updating task:', input.id, input.data);
		// In real implementation, fetch from storage and merge
		return {} as FlowsTask;
	}
}

/**
 * Example: Type guards for runtime checks
 */
export function isJourney(entity: unknown): entity is FlowsJourney {
	return (
		typeof entity === 'object' &&
		entity !== null &&
		'title' in entity &&
		'status' in entity &&
		'invited_at' in entity &&
		['invited', 'active', 'completed', 'cancelled', 'archived'].includes(
			(entity as FlowsJourney).status
		)
	);
}

export function isTask(entity: unknown): entity is FlowsTask {
	return (
		typeof entity === 'object' &&
		entity !== null &&
		'journey_id' in entity &&
		'title' in entity &&
		'status' in entity &&
		['pending', 'in_progress', 'completed', 'cancelled', 'blocked'].includes(
			(entity as FlowsTask).status
		)
	);
}

/**
 * Example: Extend metadata types for app-specific data
 */
export interface OnboardingJourney extends FlowsJourney {
	metadata: {
		department: string;
		start_date: string;
		location: string;
		manager_id: string;
		equipment_needed?: string[];
	};
}

/**
 * Example: Helper to create typed journey from form data
 */
export function createOnboardingJourney(formData: {
	title: string;
	employee_email: string;
	department: string;
	start_date: string;
	location: string;
	manager_id: string;
}): FlowsEntityCreate<OnboardingJourney> {
	return {
		client_id: 'demo',
		app_id: 'flows',
		title: formData.title,
		description: `Onboarding for ${formData.employee_email}`,
		status: 'invited',
		invited_at: new Date(),
		owner_id: formData.manager_id,
		participants: [formData.employee_email, formData.manager_id],
		primary_participant_id: formData.employee_email,
		metadata: {
			department: formData.department,
			start_date: formData.start_date,
			location: formData.location,
			manager_id: formData.manager_id
		}
	};
}
